Lesson 4
MaksimPW/blog-on-react pull request #4
Opened 2017-07-19 12:17 UTC by MaksimPW

2017-07-20 10:06 UTC, blackleadsu requested changes
Проследи также, чтобы линтер был доволен:
`./node_modules/eslint/bin/eslint.js ./src/client/app --ext js,jsx`

2017-07-20 10:06 UTC, blackleaden commented on index.html
> +    <script src="src/client/public/bundle.js" type="text/javascript"></script>
Здесь следует указать `/assets/bundle.js` так как именно этот путь указан как publicPath в конфиге webPack'а. Тогда хотрелоад будет работать корректно, без сборки бандла вручную.

2017-07-20 10:16 UTC, MaksimPW commented on index.html
> +    <script src="src/client/public/bundle.js" type="text/javascript"></script>
Спасибо, выручил!)

2017-07-20 13:03 UTC, blackleadsu requested changes
Линтер всё еще не доволен. 
Рекомендую использовать абсолютные пути к модулям. Можно указать корень у webPack указать не `./src` а `/src/client/app`, но я рекомендую задуматься, нужна ли такая вложенность? Bundle по смыслу не должен находиться в src, а всё, что не client по идее должно выноситься в другие репозитории. Вспомогательные вещи будут в `./initializers`, `./tests` и т.п. Как-то так)

Возможно, в линтере нужно будет добавить в блок "settings" настройки типа таких:
```
    "import/extensions": [ '.js', '.jsx'],
    "import/resolver": {
      "node": {
        'extensions': ['.js', '.jsx'],
        "moduleDirectory": [ ... ]
      }
```
Подробнее можно посмотреть в документации линтера.

2017-07-21 09:26 UTC, blackleadsu approved these changes

2017-07-21 13:39 UTC, merged