Lesson 5
MaksimPW/blog-on-react pull request #5
Opened 2017-07-26 17:51 UTC by MaksimPW

2017-07-28 08:24 UTC, blackleadsu requested changes
Есть замечания, в том числе нужно исправить замечания от eslint. 
Лайк на API -- не обязательно.

2017-07-28 08:24 UTC, blackleaden commented on src/client/app/routes/paths.js
> +export const postsPath = (id = ':id') => `/posts/${id}`;
Этот файл логично вынести в /helpers/

2017-07-28 08:24 UTC, blackleaden commented on src/client/app/components/containers/BlogPage.jsx
> +      'http://localhost:3031',
Пути к API лучше вынести в константы.

2017-07-28 08:24 UTC, blackleaden commented on src/client/app/components/containers/BlogPage.jsx
>    likeAdd(postId) {
Лайки перестали работать, так как состояние сбрасывается при переходе со страницы на страницу. В качестве допа рекомендую реализовать инкремент лайка на стороне API.

2017-07-28 08:24 UTC, blackleaden commented on src/client/app/components/layouts/MainLayout.js
> +    <a href='#' onClick={() => history.goBack()}>Назад</a>
GoBackButton работает нелогично -- например, "назад" с главной, или "назад" при переходе на страницу поста по прямой ссылке. Можно сделать с помощью react-router Link, а на главной вообще убрать. 
...гораздо интереснее задача с кнопкой становится, если взять доп.задание с пагинацией и/или поиском.

2017-08-15 08:14 UTC, MaksimPW commented on src/client/app/components/containers/BlogPage.jsx
>    likeAdd(postId) {
Сделал на стороне API. Будут отдельные пользователи? Хочется все же не инкремент лайка сделать, а toggle

2017-08-15 15:09 UTC, blackleadsu approved these changes

2017-08-15 15:09 UTC, blackleaden commented on src/client/app/helpers/Api.js
> +  addLike: (id) => 'http://localhost:3000/posts/'.concat(id, '/add_like'),
Рекомендую использовать шаблонные строки из es6 вместо concat

2017-08-15 15:51 UTC, merged