Lesson 6
MaksimPW/blog-on-react pull request #6
Opened 2017-08-21 17:00 UTC by MaksimPW

2017-08-22 15:59 UTC, index01d requested changes

2017-08-22 15:59 UTC, index01d commented on src/client/app/actions/Post.js
> +const errorLikePost = () => ({
совмести like-action'ы в один модуль. Различие на posts/post не нужно

2017-08-22 15:59 UTC, index01d commented on src/client/app/components/containers/Post.jsx
> +                likeAdd: () => likeAdd(post.id)
реализуй LikeContainer, тогда не придется таскать likeAdd по иерархии

2017-08-22 15:59 UTC, index01d commented on src/client/app/components/ui/BlogItem.jsx
> +      <LikeContainer count={likes} postId={id} likeAdd={likeAdd} />
раз есть контейнер, то не нужно передавать тут атрибуты кроме postId. Все остальные можно сформировать и передать внутри контейнера

2017-08-22 15:59 UTC, index01d commented on src/client/app/components/ui/Like.jsx
> +      this.renderLike(count, postId, likeAdd)
зачем здесь выносить это в функцию?

2017-08-23 06:06 UTC, MaksimPW commented on src/client/app/components/ui/Like.jsx
> +      this.renderLike(count, postId, likeAdd)
4:1  warning  Component should be written as a pure function  react/prefer-stateless-function
4:1  warning  Component should be written as a pure function  react/prefer-stateless-function

2017-08-23 07:02 UTC, MaksimPW commented on src/client/app/actions/Post.js
> +const errorLikePost = () => ({
Совместил. Получил вызов и обновление в двух редусерах state. В одном это entry, в другом entries - из-за этого пошли ошибки. Поэтому я лучше верну все на место, чтобы для двух reducers были разные.

2017-08-23 09:17 UTC, index01d commented on src/client/app/actions/Post.js
> +const errorLikePost = () => ({
нет, давай лучше посмотрим ошибки

2017-08-23 09:18 UTC, index01d commented on src/client/app/components/ui/Like.jsx
> +      this.renderLike(count, postId, likeAdd)
все правильно, а зачем делать этот компонент классом?

2017-08-23 12:10 UTC, MaksimPW commented on src/client/app/actions/Post.js
> +const errorLikePost = () => ({
Зачем? Я уже посмотрел. Они в прошлом коммите d11f337.
Проблема в том, что если использовать один like-action, то результат будет приходить только в один из [entry, entries]. Это создает проблемы, так как для Post и Posts мы используем разные state. Для одного Post используется state.entry, для нескольких Posts используется state.entries. Значит для них нужны различные actions, которые будут кидать результат либо в entry, либо в entries в зависимости от текущего местоположения.

2017-08-23 12:31 UTC, index01d requested changes

2017-08-23 12:31 UTC, index01d commented on src/client/app/actions/Post.js
> +const errorLikePost = () => ({
> Для одного Post используется state.entry, для нескольких Posts используется state.entries. Значит для них нужны различные actions, которые будут кидать результат либо в entry

Нет в этом логики. Состояние изменяет reducer. Два reducer'a могут обработать один и тот же Like-action. Возвращать на Like нужно не сам пост, а итоговое количество. Даже если возвращается сам post, то можно пробежать в reducer'e по постам и заменить нужный

2017-08-24 08:47 UTC, blackleadsu requested changes
Движешься в правильном направлении! Но *нужно* еще проще - как с компонентом like, так и с контейнерами, экшнами и редьюсерами. Постарался иначе объяснить то, что говорил Эдуард.

Рекомендации (мои) не обязательны, но желательны).

2017-08-24 08:47 UTC, blackleaden commented on src/client/app/actions/Posts.js
> +export function fetchLikePosts(id, posts) {
Эта логика по вставке обновленного поста в список должна быть в редьюсере Posts, а не в action. А action должен быть в `actions/Like`.

**Подробнее:**
Fetch-action для лайка должен быть один и должен находиться в `actions/Like`. 
Мы одинаково лайкаем конкретный пост, где бы мы не находились: с помощью одного и того же action из `actions/Like`, который отправит запрос на одну и ту же API-точку (для конкретного поста).
Получаем результат (либо количество лайков на этом посте, либо обновленный пост). 
Далее этот action обрабатывают два редюсера и заменяют этот пост как в списке (в `reducers/Posts`), так и в `reducers/Post`.

2017-08-24 08:47 UTC, blackleaden commented on src/client/app/actions/Post.js
> +export function fetchLikePost(id) {
Этот action должен быть в `actions/Like`.
См. подробный комментарий в `actions/Posts`;

2017-08-24 08:47 UTC, blackleaden commented on src/client/app/containers/ChartContainer.js
> +import TextBox from './../components/ui/TextBox';
*Рекомендация*: если настроить абсолютные пути к модулям, будет несколько удобнее.

2017-08-24 08:47 UTC, blackleaden commented on src/client/app/containers/LikeContainer.jsx
> +import { fetchLikePosts } from './../actions/Posts';
Like-action должен быть один, его влияние на состояние -- дальнейшая обработка в reducer'ах поста, постов и прочих (что возможно) -- нас здесь не касается. 

Это важный момент: *в контейнере не должно быть логики, связанной с обработкой action*. Контейнер просто "запаковывает" нужные действия и свойства и передает их  компоненту. Ни контейнер, ни компонент не знают, как и в скольких reducer'ах в последствии будет обработано действие.

Не должно быть подобного `postType` -- кнопка лайка должна знать только id поста, который она инкрементирует. Что будет, если у нас появятся избранные посты отдельным списком? Последние посты? Кнопке должно быть без разницы, где она находится, если она выполняет одно и то же действие.

Также см. подробный комментарий в `actions/Posts`.

2017-08-24 08:47 UTC, blackleaden commented on src/client/app/components/ui/Like.jsx
> +class Like extends React.Component {
Еще проще!
```
const Like = ({ addLike, count }) => (
       <div>
         <button
           className='like'
           onClick={ () => addLike() }>
             Like {count}
         </button>
       </div>
);
```
Поясняю: posts и postType не нужны, см.комментарии в контейнере и action'ах (*это обязательно*). А postId можно "завернуть" в коллбэк addLike на уровне контейнера (*это рекомендация*).

2017-08-24 08:47 UTC, blackleaden commented on src/client/app/containers/LikeContainer.jsx
> +export default connect(stateToProps, actionsToProps)(Like);
*Рекомендация*
Используя mergeProps можно сделать `addLike = () => actionProps.addLike(stateProps.postId)`; Это позволит не передавать вниз postId. 
Такое полезно не только для упрощения кода презентационных компонентов: это сводит кнопку лайка к стандартному для ui-кнопок интерфейсу -- коллбэк на onClick + содержимое.

2017-08-24 08:52 UTC, blackleaden commented on src/client/app/containers/LikeContainer.jsx
> +export default connect(stateToProps, actionsToProps)(Like);
https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options

2017-08-25 06:37 UTC, blackleadsu approved these changes

2017-08-25 11:07 UTC, merged